language: ruby
rvm:
- 2.2.2
services:
  - redis-server
addons:
  postgresql: '9.3'
test:
  adapter: postgresql
  database: cuperu_test
  username: postgres
before_script:
  - psql -c 'create database cuperu_test;' -U postgres
