default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cuperu_development

test:
  <<: *default
  database: cuperu_test

production:
  <<: *default
  database: cuperu_production
  username: cuperu
  password: <%= ENV['CUPERU_DATABASE_PASSWORD'] %>
